/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AAlert: typeof import('ant-design-vue/es')['Alert']
    AButton: typeof import('ant-design-vue/es')['Button']
    ACard: typeof import('ant-design-vue/es')['Card']
    ACardMeta: typeof import('ant-design-vue/es')['CardMeta']
    ACarousel: typeof import('ant-design-vue/es')['Carousel']
    ACol: typeof import('ant-design-vue/es')['Col']
    AForm: typeof import('ant-design-vue/es')['Form']
    AFormItem: typeof import('ant-design-vue/es')['FormItem']
    AInput: typeof import('ant-design-vue/es')['Input']
    AInputPassword: typeof import('ant-design-vue/es')['InputPassword']
    ALayout: typeof import('ant-design-vue/es')['Layout']
    ALayoutContent: typeof import('ant-design-vue/es')['LayoutContent']
    ALayoutFooter: typeof import('ant-design-vue/es')['LayoutFooter']
    ALayoutHeader: typeof import('ant-design-vue/es')['LayoutHeader']
    ARow: typeof import('ant-design-vue/es')['Row']
    Button: typeof import('./src/components/button/button.vue')['default']
    CommentList: typeof import('./src/components/comment/CommentList.vue')['default']
    Composition: typeof import('./src/components/composition.vue')['default']
    CompositionExample: typeof import('./src/components/compositionExample.vue')['default']
    Content: typeof import('./src/components/layout/Content.vue')['default']
    Footer: typeof import('./src/components/layout/Footer.vue')['default']
    Header: typeof import('./src/components/layout/Header.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    IconCommunity: typeof import('./src/components/icons/IconCommunity.vue')['default']
    IconDocumentation: typeof import('./src/components/icons/IconDocumentation.vue')['default']
    IconEcosystem: typeof import('./src/components/icons/IconEcosystem.vue')['default']
    IconSupport: typeof import('./src/components/icons/IconSupport.vue')['default']
    IconTooling: typeof import('./src/components/icons/IconTooling.vue')['default']
    Layout: typeof import('./src/components/layout/Layout.vue')['default']
    LearnTs: typeof import('./src/components/learnTs.vue')['default']
    MyButton: typeof import('./src/components/button/MyButton.vue')['default']
    PageHeader: typeof import('./src/components/page-header/PageHeader.vue')['default']
    ProxyTest: typeof import('./src/components/ProxyTest.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Scorll: typeof import('./src/components/scorll.vue')['default']
    Scroll: typeof import('./src/components/scroll.vue')['default']
    Sider: typeof import('./src/components/layout/Sider.vue')['default']
    Slider: typeof import('./src/components/slider/Slider.vue')['default']
    TheWelcome: typeof import('./src/components/TheWelcome.vue')['default']
    TodoList: typeof import('./src/components/TodoList.vue')['default']
    WelcomeItem: typeof import('./src/components/WelcomeItem.vue')['default']
  }
}
